---
title: "Restaurant Event Dashboard"
output: flexdashboard::flex_dashboard
---

```{r setup, include = FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(lubridate)
Perm_event <- read_csv("https://data.cityofnewyork.us/resource/tvpp-9vvx.csv")
Restaurant <- read_csv("https://data.cityofnewyork.us/resource/43nn-pn8j.csv")
knitr::opts_chunk$set(fig.width = 5, fig.asp = 1/3)
```

## Column 1

### Event Length

```{r}
Perm_events1 <- Perm_event%>%
  mutate(Perm_event,length_event_hr=hour(end_date_time)-hour(start_date_time),
         length_event_day=day(end_date_time)-day(start_date_time))
by_borough <- group_by(Perm_events1,event_borough)
avg_lengths <- summarise(by_borough,
                        count=n(),
                        length=mean(length_event_hr,na.rm = TRUE))

ggplot(data=avg_lengths,mapping=aes(x=event_borough,y=length))+
  geom_boxplot()+
  labs(title = "Longest average events take place in Brooklyn")

```

### Cuisine Options

```{r}
by_boroughs <- group_by(Restaurant,boro)
sum_cuisines <- summarise(by_boroughs,
                        count=n())
sum_cuisines
                        
ggplot(data=sum_cuisines,mapping=aes(x=boro,y=count))+
  geom_boxplot()+
  labs(title = "Most cuisine options are in Manhattan")
```

## Column 2

### Cuisine Description

```{r}
Restaurant%>%
  mutate(cuisine_descriptions=fct_collapse(cuisine_description,
                                          USA= c("American","Bagels/Pretzels"),
                                          BBQ= c("Hamburgers","Barbecue","Tex-Mex","Steak","Hotdogs/Pretzels"),
                                          Deli= c("Delicatessen","Jewish/Kosher"),
                                          Other= c("Other","Not Listed/Not Applicable"),
                                          Dessert= c("Donuts","Bakery","Ice Cream, Gelato, Yogurt, Ices"),
                                          Drinks= c("Café/Coffee/Tea","Juice, Smoothies, Fruit Salads","Bottled beverages, including water, sodas, juices, etc.")))%>%
  count(cuisine_descriptions,sort=TRUE)%>%
  DT::datatable()
```

### Event Length 

```{r}
Perm_events1 <- Perm_event%>%
  mutate(Perm_event,length_event_hr=hour(end_date_time)-hour(start_date_time),
         length_event_day=day(end_date_time)-day(start_date_time))
Perm_events2 <- Perm_events1%>%
  mutate(Perm_events1,length_event_hr=hours(length_event_hr))
Perm_events2%>%
  select(event_borough,start_date_time,end_date_time,length_event_hr,length_event_day)%>%
  DT::datatable()
```
